Repository ascopes/java-compiler-testing, pull requests merged in 2022-12, with the labels that each got.

#185 Fixed typo
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/AbstractJctCompiler.java
Labels: documentation, housekeeping

#187 [Fixed] - Moved abstract jct compiler out of the impl package #186
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/JavacJctCompilerImpl.java
Labels: documentation, housekeeping, 👕 tiny

#191 (on hold) Implement mutation tests
  .github/workflows/main.yml
  java-compiler-testing/pom.xml
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/IntegrationTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicLegacyCompilationIntegrationTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicModuleCompilationIntegrationTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/integration/BasicMultiModuleCompilationIntegrationTest.java
  pom.xml
Labels: testing, ci, help needed
