Repository ascopes/java-compiler-testing, pull requests merged in 2023-01, with the labels that each got.

#221 Make LazyTest stricter to detect and avoid flakes
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/LazyTest.java
Labels: testing, 👕 small

#237 Add documentation to AbstractCompilersProvider
  java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/AbstractCompilersProvider.java
Labels: documentation

#232 adds two unit tests for JctFileManagerImpl module.
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerImplTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/package-info.java
Labels: testing

#264 Remove -implicit flag from default compilation
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/JavacJctCompilerImpl.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/javac/JavacJctCompilerImplTest.java
Labels: 👕 tiny

#266 Add ability to limit the classes that actually get compiled
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctJsr199Interop.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/JctCompilerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/impl/JctJsr199InteropTest.java
Labels: new feature, 👕 small

#268 Support project loom threads properly
  java-compiler-testing/src/main/java/io/github/ascopes/jct/diagnostics/TracingDiagnosticListener.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/LoggingFileManagerProxy.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/LoomPolyfill.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/Fixtures.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/diagnostics/TraceDiagnosticTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/diagnostics/TracingDiagnosticListenerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/LoomPolyfillTest.java
Labels: optimisations, 👕 small

#269 Optimise URL extraction from classloader
  java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/PackageContainerGroupUrlClassLoader.java
Labels: housekeeping, trimming fat, 👕 tiny

#267 Speed up builds
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .mvn/jvm.config
  .mvn/maven.config
  mvnw
  scripts/prepare-test-outputs-for-merge.sh
Labels: ci

#271 Enable JDK 21 in builds
  .github/workflows/build.yml
  README.md
Labels: housekeeping

#273 Add ability to customise the names of compiler objects
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
Labels: new feature, 👕 small

#274 Versioning strategies in Junit support.
  java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/AbstractCompilersProvider.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilerTest.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilersProvider.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/VersionStrategy.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/AbstractCompilersProviderTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/JavacCompilersProviderTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/junit/VersionStrategyTest.java
Labels: new feature

#278 Use factory pattern to initialise flag and JavaCompiler objects
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctFlagBuilderFactory.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/Jsr199CompilerFactory.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/JavacJctCompilerImpl.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/javac/JavacJctCompilerImplTest.java
Labels: housekeeping, new feature, 👕 medium

#279 Remove JSR-199 Interop class and reimplement object model.
  .mvn/checkstyle/checkstyle.xml
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompilationFactory.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactoryImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctJsr199Interop.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/JavacJctCompilerImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/diagnostics/TeeWriter.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManagerFactory.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/ModuleLocation.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerAnnotationProcessorClassPathConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerConfigurerChain.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmClassPathConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmClassPathModuleConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmModulePathConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmPlatformClassPathConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerJvmSystemModulesConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerLoggingProxyConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerRequiredLocationsConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerWorkspaceConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/package-info.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerFactoryImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerImpl.java
  java-compiler-testing/src/main/java/module-info.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/impl/JctJsr199InteropTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/javac/JavacJctCompilerImplTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/diagnostics/TeeWriterTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerAnnotationProcessorClassPathConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerConfigurerChainTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerJvmClassPathConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerJvmClassPathModuleConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerJvmModulePathConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerJvmPlatformClassPathConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerJvmSystemModulesConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerLoggingProxyConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerRequiredLocationsConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerWorkspaceConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerImplTest.java
Labels: housekeeping, testing, optimisations, 👕 large

#286 Make container groups list collections rather than iterables.
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactoryImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/PackageContainerGroup.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/AbstractPackageContainerGroup.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerImpl.java
Labels: optimisations, trimming fat, 👕 small

#287 Simplify the JctFileManagerImpl class into a separate repository
  java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ContainerGroupRepositoryImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/diagnostics/TeeWriter.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config/JctFileManagerAnnotationProcessorClassPathConfigurer.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/ModuleDiscoverer.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/config/JctFileManagerAnnotationProcessorClassPathConfigurerTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerImplTest.java
Labels: housekeeping, optimisations, trimming fat, 👕 medium

#295 Do not open modules to JUnit
  java-compiler-testing/src/main/java/module-info.java
Labels: housekeeping

#296 JctFileManagerFactoryImpl tests
  java-compiler-testing/src/main/java/io/github/ascopes/jct/diagnostics/TracingDiagnosticListener.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/JctFileManager.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerFactoryImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/impl/JctFileManagerImpl.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/junit/JavacCompilersProvider.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/VisibleForTestingOnly.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/impl/JctFileManagerFactoryImplTest.java
Labels: housekeeping, testing, 👕 tiny

#297 Add test pack for LoggingFileManagerProxy
  java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/LoggingFileManagerProxy.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/LoomPolyfill.java
  java-compiler-testing/src/main/java/io/github/ascopes/jct/utils/ToStringBuilder.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/Fixtures.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/Slf4jLoggerFake.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/LoggingFileManagerProxyTest.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/LoomPolyfillTest.java
Labels: housekeeping, testing

#298 Module discoverer tests
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/utils/ModuleDiscovererTest.java
Labels: testing, 👕 tiny

#300 Replace mockito-inline with mockito-core
  java-compiler-testing/pom.xml
Labels: housekeeping

#301 Add missing AbstractJctCompiler coverage
  java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/AbstractJctCompiler.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/compilers/AbstractJctCompilerTest.java
Labels: testing

#302 Add ModuleLocation tests
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/Fixtures.java
  java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/unit/filemanagers/ModuleLocationTest.java
Labels: testing
